#pragma once

#include "ecs/system/AudioManager.h"
#include "ecs/system/PhysicsManager.h"
#include "ecs/system/SensorManager.h"
#include "ecs/system/LifetimeManager.h"
#include "ecs/system/PlayerManager.h"
#include "ecs/system/EnemyManager.h"
#include "ecs/system/CollisionManager.h"
#include "ecs/system/CameraManager.h"
#include "ecs/system/HierarchyManager.h"
#include "ecs/system/TextManager.h"
#include "ecs/system/InteractionManager.h"
#include "ecs/system/SpriteManager.h"
#include "ecs/system/RenderManager.h"